---
- name: How to prompt for variables
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: "yourpassword"
      prompt: "What is your password?"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
      default: "qwerty"

  tasks:
    - name: Print out the password
      debug:
        msg: "{{ yourpassword }}"
